/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ModalViewActivityContacts: typeof import('./src/components/ViewActivity/ModalViewActivityContacts.vue')['default']
    ModalViewActivityDates: typeof import('./src/components/ViewActivity/ModalViewActivityDates.vue')['default']
    ModalViewActivityLocation: typeof import('./src/components/ViewActivity/ModalViewActivityLocation.vue')['default']
    ModalViewActivityNotes: typeof import('./src/components/ViewActivity/ModalViewActivityNotes.vue')['default']
    ModalViewActivityPayments: typeof import('./src/components/ViewActivity/ModalViewActivityPayments.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    Page: typeof import('./src/components/Page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
